# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b68e813f0e10a5312656017c1007db373d1cedc1ee9ba45128dc42264516ba2005442bec5b33c4651cf9b3bd92203541aeb39e0bae23723cce68d74e5effcd43

test:
  secret_key_base: 850a37428c379bd2149e826eb1b27408ec0370059d0624c156bc76a43ba982c1dbab719586425604f64e1e655c6a49c57c3bc0ff46d88d7f79067ad799f3c296

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
